[tool.poetry]
name = "litellm-proxy-extras"
version = "0.1.0"
description = ""
authors = ["Krrish Dholakia <krrishdholakia@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
