repos:
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # The version of flake8 to use
    hooks:
    -  id: flake8
       exclude: ^litellm/tests/|^litellm/proxy/proxy_cli.py|^litellm/proxy/tests/
       additional_dependencies: [flake8-print]
       files: litellm/.*\.py
-   repo: local
    hooks:
    -   id: check-files-match
        name: Check if files match
        entry: python3 ci_cd/check_files_match.py
        language: system
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: python3 -m mypy --ignore-missing-imports
        language: system
        types: [python]
        files: ^litellm/
    -   id: check-file-length
        name: Check file length
        entry: python check_file_length.py
        args: ["10000"]  # set your desired maximum number of lines
        language: python
        files: litellm/.*\.py
        exclude: ^litellm/tests/