repos:
-   repo: local
    hooks:
    -   id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        files: ^(litellm/|litellm_proxy_extras/|enterprise/)
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        files: (litellm/|litellm_proxy_extras/|enterprise/).*\.py
        exclude: ^litellm/__init__.py$
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        files: (litellm/|litellm_proxy_extras/|enterprise/).*\.py
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # The version of flake8 to use
    hooks:
    -  id: flake8
       exclude: ^litellm/tests/|^litellm/proxy/tests/|^litellm/tests/test_litellm/|^tests/test_litellm/|^tests/enterprise/
       additional_dependencies: [flake8-print]
       files: (litellm/|litellm_proxy_extras/|enterprise/).*\.py
-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
        files: ^(pyproject.toml|litellm-proxy-extras/pyproject.toml)$
-   repo: local
    hooks:
    -   id: check-files-match
        name: Check if files match
        entry: python3 ci_cd/check_files_match.py
        language: system