# fly.toml app configuration file generated for lite-llm on 2025-11-16T09:36:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lite-llm'
primary_region = 'nrt'
swap_size_mb = 512

[[vm]]
  size = 'shared-cpu-1x'
  memory = 256

[build]
  dockerfile = "deploy/Dockerfile.ghcr_base"

[env]
  # Set non-root flag
  LITELLM_NON_ROOT = "true"
  NODE_ENV = "production"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  path = "/health/liveliness"
  protocol = "http"
  timeout = "10s"
