site_name: liteLLM
nav:
  - âš¡ Getting Started:
    - Installation & Quick Start: index.md
    - completion():
      - Input - Request Body: input.md
  - ðŸ¤– Supported LLM APIs: 
    - Supported Completion & Chat APIs: supported.md
    - Supported Embedding APIs: supported_embedding.md
  - ðŸ’¾ Callbacks - Logging Output: 
    - Quick Start: advanced.md
    - Output Integrations: client_integrations.md
    - Helicone Tutorial: helicone_integration.md
  - ðŸ’¡ Support:
    - Troubleshooting & Help: troubleshoot.md
    - Contact Us: contact.md
  - Contributing:
    - Contributing to Docs: contributing.md

theme: readthedocs
