site_name: liteLLM
nav:
  - âš¡ Getting Started:
    - Installation & Quick Start: index.md
    - completion():
      - Input - Request Body: input.md
      - Output - Response Object: output.md
      - Streaming & Async Calls: stream.md
    - token usage:
      - Helper Functions: token_usage.md
  - ğŸ¤– Supported LLM APIs: 
    - Supported Completion & Chat APIs: supported.md
    - Supported Embedding APIs: supported_embedding.md
  - ğŸƒâ€â™‚ï¸ Fetching Inputs: 
    - Secret Managers: secret.md
  - ğŸ’¾ Callbacks - Logging Output: 
    - Quick Start: advanced.md
    - Output Integrations: client_integrations.md
    - LLMonitor Tutorial: llmonitor_integration.md
    - Traceloop Tutorial: traceloop_integration.md
    - Helicone Tutorial: helicone_integration.md
    - Supabase Tutorial: supabase_integration.md
    - BerriSpend Tutorial: berrispend_integration.md
  - ğŸ’¡ Support:
    - Troubleshooting & Help: troubleshoot.md
    - Contact Us: contact.md
  - Contributing:
    - Contributing to Docs: contributing.md

theme: readthedocs
