model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: sk-fake-key

general_settings:
  master_key: sk-1234
  database_url: "sqlite:///litellm_test.db"
  
litellm_settings:
  drop_params: True
  telemetry: False
