blank_issues_enabled: true
contact_links:
  - name: Schedule Demo
    url: https://calendly.com/d/cx9p-5yf-2nm/litellm-introductions
    about: Speak directly with Krrish and Ishaan, the founders, to discuss issues, share feedback, or explore improvements for LiteLLM
  - name: Discord
    url: https://discord.com/invite/wuPM9dRgDw
    about: Join 250+ LiteLLM community members! 
