# This job runs the prisma migrations for the LiteLLM DB.

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "litellm.fullname" . }}-migrations
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: prisma-migrations
          image: "ghcr.io/berriai/litellm:main-stable"
          command: ["python", "litellm/proxy/prisma_migration.py"]
          workingDir: "/app"
          env:
            {{- if .Values.db.deployStandalone }}
            - name: DATABASE_URL
              value: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql/{{ .Values.postgresql.auth.database }}
            {{- else if .Values.db.useExisting }}
            - name: DATABASE_URL
              value: {{ .Values.db.url | quote }}
            {{- end }}
            - name: DISABLE_SCHEMA_UPDATE
              value: "{{ .Values.migrationJob.disableSchemaUpdate }}"
      restartPolicy: OnFailure
  backoffLimit: {{ .Values.migrationJob.backoffLimit }}
