{{- if and (eq .Values.serviceMonitor.enabled true) (eq .Values.serviceMonitor.secret.create true) .Values.serviceMonitor.secret.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm.fullname" . }}-servicemonitor-token
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
data:
  token: {{ .Values.serviceMonitor.secret.value | b64enc }}
type: Opaque
{{- end }}
