{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litellm.serviceAccountName" . }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.migrationJob.enabled }}
    {{- if .Values.migrationJob.hooks.argocd.enabled }}
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    {{- end }}
    {{- if .Values.migrationJob.hooks.helm.enabled }}
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/hook-weight: {{ .Values.migrationJob.hooks.helm.weight | default "1" | quote }}
    {{- end }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
